import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Uploader from "../../component/Uploader";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Images upload</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Uploader />
		</div>
	);
};

export default Home;
